name: GamemodeGive
main: ru.rexlite.GamemodeGive
version: "1.0"
api: ["1.1.0", "1.0.13"]
author: "Criex"
commands:
  gamemodesgive:
    description: "Turn on/turn off creative game mode to others players"
    permission: "gamemode.give"
    aliases: ["gmgive"]
permissions:
  gamemode.give:
    default: op
